# Generated by Django 2.2.2 on 2019-06-29 08:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('summary', models.TextField()),
                ('productId', models.CharField(max_length=100)),
                ('userId', models.CharField(max_length=100)),
                ('profileName', models.CharField(max_length=100)),
                ('helpfulness', models.CharField(max_length=10)),
                ('score', models.FloatField(max_length=10)),
                ('time', models.IntegerField()),
            ],
        ),
    ]
